### PR TITLE
Fedora support + remove build warnings

### PR DESCRIPTION
**Pull request by Victor333Huesca**
Add support for _**Fedora 39**_ (tested under `WSL`).

Use raw literal in python regex strings, this is the right way to escape regex's special characters in python.
Otherwise, python first tries to escape the characters itself, fails and issue a warning which is confusing to user.

Checklist
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Have tested the modifications

### CODE REVIEW

**Comment by Victor333Huesca** [comment]
Hi,
Thanks for the review!
I notice you did `forced-pushed` 2 commits after, thus dropping this merge.
Was it intentional, is there a bug with this patch?

**Comment by Howard20181** [comment]
In some python scripts wrong use of raw strings may break escape characters

**Comment by Victor333Huesca** [comment]
According to the official python documentation: https://docs.python.org/3/library/re.html
> Regular expressions use the backslash character ('\') to indicate special forms or to allow special characters to be used without invoking their special meaning. This collides with Python’s usage of the same character for the same purpose in string literals; for example, to match a literal backslash, one might have to write '\\\\' as the pattern string, because the regular expression must be \\, and each backslash must be expressed as \\ inside a regular Python string literal. Also, please note that any invalid escape sequences in Python’s usage of the backslash in string literals now generate a SyntaxWarning and in the future this will become a SyntaxError. This behaviour will happen even if it is a valid escape sequence for a regular expression.

> The solution is to use Python’s raw string notation for regular expression patterns; backslashes are not handled in any special way in a string literal prefixed with 'r'. So r"\n" is a two-character string containing '\' and 'n', while "\n" is a one-character string containing a newline. Usually patterns will be expressed in Python code using this raw string notation.

**Comment by Howard20181** [comment]
When you use raw string, you should remove `\` from strings.

You can make changes to *.sh to make Fedora support. Don't commit unrelated changes to the same pull request

**Pull request merged**
