### PR TITLE
make link for wsa res to reduce system space

### PR DESCRIPTION
**Pull request by SsageParuders**
## Make link for wsa res to save system space

1. WSA's userdata had stored at `%LOCALAPPDATA%\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe`
2. And it maybe huge after long time.
3. Some users may not have a lot of system disk space.
4. So, why not make a link for it to save system disk space?

### CODE REVIEW

**Comment by Howard20181** [comment]
1. This may cause performance degradation
1. There are many combinations of device configurations and you can't do this for all users
1. WSA may be used on the same system for multiple users at the same time
1. Data should not be mixed with the installation directory

**Comment by SsageParuders** [comment]
Ok, got it.
But how about we let the user decide where the userdata will be installed?

---

Finally, Thinks for such a great project~

It helps me a lot.

**Comment by Howard20181** [comment]
I think it can be written into the wiki, and now there are many meaningful questions that have been asked before that can be written in.

**Comment by SsageParuders** [comment]
Yes.

For Developers, it is easy to save system disk space by link.

But here still lots of nomnal users.
- they don't know how to save system disk space
- they don't know how to make a link
- their system disk space will be less and less
- and they want to use wsa.

Those nomnal users want to use wsa, but they are afraid for system disk space, since it is value.

---
Thinks a lot for LSPosed Developers~

**Pull request closed without merging**
