### PR TITLE
Add option to skip fix system props

### PR DESCRIPTION
**Pull request by s1204IT**
#### Checklist
- [x] Have tested the modifications

---
~~We're verifying details so please wait...~~
Verified.

### CODE REVIEW

**Comment by Howard20181** [comment]
If not modified, a fresh installation will not be able to log in to your Google account.

**Comment by s1204IT** [comment]
Yes, we know, of course.
But it can be easily solved.

Usually, people who use MagiskOnWSA don't want this feature.

**Comment by Howard20181** [comment]
Then they can choose not to integrate GApps
Maybe we can make not integrating GApps the default option

**Comment by s1204IT** [comment]
What we want to do is keep WSA's original system props and get GApps working.

There will be little benefit to that.
However, it is true that very few GApps users want that feature.

Still, I added this option new to apply that minority opinion, including mine.

**Comment by Howard20181** [comment]
> keep WSA's original system props and get GApps working

I don't think this is feasible.

Maybe you can make it a command line parameter only
But don't show it on `run.sh` where you don't need to enter the command, and let advanced users apply this option manually and print a warning.

**Comment by s1204IT** [comment]
@Howard20181 
How about this?

**Pull request merged**
