### PR TITLE
Rewrite random character generator

### PR DESCRIPTION
**Pull request by lalishansh**
Fix for me

### CODE REVIEW

**Comment by GroundFishles** [comment]
What about this option?
`haveged -n $((${1:-32}*512)) --file - 2>/dev/null | tr -dc '[:lower:]' | fold -w "$1" | head -n 1`

**Comment by GroundFishles** [comment]
There is another option:
`tr -dc '[:lower:]' </dev/urandom | head -c "$1"`

**Comment by Howard20181** [comment]
Is there something wrong with the original code? What is this change to fix?
I haven't seen any bug reports yet.

Also, the service name should be in all lowercase letters without numbers

**Comment by lalishansh** [comment]
Somehow, wsl Ubuntu always got at that point so I compared it with other forks (like: https://github.com/PeterNjeim), after that it started working again

**Comment by PeterNjeim** [comment]
Indeed that line always got stuck, and so that's why I changed it. Unfortunately that fork just got banned sometime within the past 16 hours, contacting them to see what the problem is

**Review by Howard20181 — APPROVED** [review]

**Pull request merged**
