### PR TITLE
Support integrate KernelSU

### PR DESCRIPTION
**Pull request by Howard20181**

### CODE REVIEW

**Comment by YT-Advanced** [comment]
hmm, can we use KernelSU with Magisk ? If it can, please share me the command of build.sh

**Comment by Howard20181** [comment]
> hmm, can we use KernelSU with Magisk ? If it can, please share me the command of build.sh

No

**Comment by YT-Advanced** [comment]
> No

Oh thanks, I have tested and it don't have manager :((( Can you add it to the patch, thanks

**Comment by Almighty188** [comment]
> > hmm, can we use KernelSU with Magisk ? If it can, please share me the command of build.sh
> 
> No

When ./run.sh is used, it appears that for the root solution, it has a * on both the Magisk and KernelSU as this is what it looks like with a repo as of 30 minutes ago.  
image

**Comment by Howard20181** [comment]
> > > hmm, can we use KernelSU with Magisk ? If it can, please share me the command of build.sh
> > 
> > 
> > No
> 
> When ./run.sh is used, it appears that for the root solution, it has a * on both the Magisk and KernelSU as this is what it looks like with a repo as of 30 minutes ago. image

Fixed

**Pull request merged**
