### PR TITLE
Minor Changes

### PR DESCRIPTION
**Pull request by s1204IT**
- Fix typo "Amazon App`s`tore"
- Add link to Microsoft Store for Ubuntu
   - I tried a direct link, but it didn't work.
   - Ex: ms-windows-store://pdp/?ProductId=9MTTCL66CPXJ&mode=mini
- May be able to fix additional issues
    - https://github.com/LSPosed/MagiskOnWSALocal/issues/61

### CODE REVIEW

**Comment by Howard20181** [comment]
Perhaps we could point to [the search page](https://apps.microsoft.com/store/search?publisher=Canonical%20Group%20Limited) and let users choose for themselves.

**Comment by s1204IT** [comment]
That's certainly true.
Now make an additional commit based on that.

**Comment by s1204IT** [comment]
Committed now.

**Comment by s1204IT** [comment]
@Howard20181 #66 
It seems that it was not `ca-certificate`.

**Comment by Howard20181** [comment]
Do not add the dependency `ca-certificates`, as it is not determined if this is the cause of the problem.

**Comment by s1204IT** [comment]
Deleted.

**Comment by s1204IT** [comment]
https://github.com/LSPosed/MagiskOnWSALocal/issues/61#issuecomment-1236162210
@Howard20181
Updating the certificates seems to have solved it, but do not add `ca-certificates`?

**Comment by Howard20181** [comment]
This seems to be a special case and should not be added to the dependency.

**Comment by miaulightouch** [comment]
`ca-certificates` was already installed by default, make it updated shouldn't be a problem.
as we won't know when microsoft update ubuntu, user would file same issues again and again.

at least, it should be deserved a note in docs.

**Pull request merged**
