### PR TITLE
Dockerfile and CI docker-publish.yml

### PR DESCRIPTION
**Pull request by galeksandrp**
`scripts/run.sh` tested on `Docker Desktop for Windows 4.11.1` (from `powershell` and `wsl` shells)
`output` tested on `Windows 11 22000.593`

### CODE REVIEW

**Comment by Howard20181** [comment]
Thanks for contributing!
This PR does not make it any less difficult to use.
It's easy to run scripts directly.
Can you describe the use case?

**Comment by galeksandrp** [comment]
I am `archlinux` (`ArchWSL` as well) user, so for me it's the simplest way to run the script.

**Comment by Howard20181** [comment]
Would it be easier to separate the installation dependency part from the script alone?

**Comment by ShellWen** [comment]
I think also Docker is the best way to build. Not all users are using Ubuntu. It's more easy to run `docker run xxx` instead git clone it, run it(may need screen) and find the files.

**Comment by intari** [comment]
Possbile another usecase:

- WSL-ubuntu 18.04 have old version version of Python3(3.6.9) and run.sh fails with

Integrate GApps
Integrate GApps done

Fix GApps prop
  File "fixGappsProp.py", line 21
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
Build: an error has occurred, exit
Cleanup Work Directory
Cleanup Download Directory

Update wsl fixes this but what if somebody builds on another linux system with old dependencies?

**Comment by Howard20181** [comment]
Some reasons for not intending to implement Docker:

1. In the process of build we need to mount the image, file operations require root privileges, which all require Docker privileged mode, which is no different from running directly.
2. The computer can use WSA means that you can use WSL2, the installation of WSL2 is more easy than Docker.
3. Users who do not use Ubuntu can manually install dependencies and then use `build.sh`.

Users should have a basic computer knowledge and know how to handle dependencies manually.

**Comment by PeterNjeim** [comment]
@galeksandrp @ShellWen @intari
If you are unable to build (or realise there's no reason to redundantly build MagiskOnWSA) then you can simply head over to my repository (https://github.com/PeterNjeim/MagiskOnWSA) and download pre-builts from the [Releases page](https://github.com/PeterNjeim/MagiskOnWSA/releases/latest). If I don't offer the exact configuration you need (rarely the case), then you can fork the repository and build whatever you want with GitHub Actions

**Pull request closed without merging**
