### PR TITLE
Added Chunk Downloader

### PR DESCRIPTION
**Pull request by m-jishnu**
Added
-  Chunk Downloader/parrel downloader
-  progress bar
- Ability to resume partially downloaded files in case of failure
  - retries to download the file 10 times before exiting
 
New Requirements
- psutil (downloader)
- reprint (progress bar)

multi-thread screenshot

Screenshot 2022-08-20 090235

single-thread screenshot

image

### CODE REVIEW

**Comment by m-jishnu** [comment]
also we can actually install wsa using the [store.rg.adguard api](https://store.rg-adguard.net/) and i found it to be more faster than the current method not sure if its due to my slow internet speed 
```
    api= "https://store.rg-adguard.net/api/GetFiles"
    data = {"type":"ProductId","url":"9P3395VX91NR","ring":"RP","lang":"en-EN"}
```
tho it depends on another site unlike the current one.

**Comment by Howard20181** [comment]
The previous version used the store.rg.adguard api, which was very unstable, so we now use our own link generation method instead.

**Comment by m-jishnu** [comment]
- Improved resume capability
  - Now even in case of file missing or corruption will resume and redownload those files
  - removed abort from those which can be resumed ( downloadwsa, download magisk)
  - Fixed typo

**Comment by Howard20181** [comment]
Why does it download WSA over and over again even though it has downloaded successfully?
image

**Comment by m-jishnu** [comment]
can you tell me how to reproduce it 

image

**Comment by Howard20181** [comment]
WSA RELEASE_TYPE=insider fast

**Comment by Howard20181** [comment]
> also can you check the download folder is it in wsa.zip or is it still in wsa.zip.00.part,wsa.zip.01.part

wsa.zip with wsa.zip.00.part,wsa.zip.01.part....

**Comment by m-jishnu** [comment]
- fixed redownloading after file completed downloading
- fixed progress bar producing bad output when retrying to download using new link in case of failure
- add a check to see if download failed based on download speed

**Comment by m-jishnu** [comment]
> 
> also can you check the download folder is it in wsa.zip or is it still in wsa.zip.00.part,wsa.zip.01.part
> 
> wsa.zip with wsa.zip.00.part,wsa.zip.01.part....

try now it should be fixed


```
while not self.completed:
    current_download = copy.deepcopy(self.doneMB)
    current_remaining = copy.deepcopy(self.remaining)
    time.sleep(10)  # check after 10 seconds if download progress
    if current_download == self.doneMB:
        raise Exception("An error has occurred!")
    if not self.singlethread: # another check for multi-thread download
        if current_remaining == self.remaining:
            raise Exception("An error has occurred!")
```
the issue was because sometimes the check ran when download was at 100% then when it checked after 10s the download was still at 100% so it raised an exception which again called the downloader due to try block (from downloadWSA.py)  which tries to redownload the file in case of failure. during this time some files might have gone missing or corrupted because the exception was raised while the appending of wsa.zip.parts into a single file was being  done, so the downloader tries to redownload these corrupted parts but as before in some case the check which was being done to see if the download was happing did the same thing  in some case while sometimes due to luck it in som cases the downloaddone wont be same after 10sec and the download succeeds, like in my case and during the download of vclibs in your case

```
while not self.completed:
    current_download = copy.deepcopy(self.doneMB)
    time.sleep(10)# check after 10 seconds if download progress
    if not self.completed:
        if current_download == self.doneMB:
            self.alive = False
            raise Exception("An error has occurred!")
        elif not self.singlethread: # another check for multi-thread 
            i = 0
            while int(self.speed) == 0:
                time.sleep(1)
                if not self.completed:
                    i+=1
                    if i % 30 == 0: #if speed is 0 MB/s for 30 seconds then raise exception
                        self.alive = False
                        raise Exception("An error has occurred due to slow/no-internet connection")
                  
```
i have now added checks in every where after a sleep to prevent this now

**Comment by Howard20181** [comment]
Now it's stuck in the WSA download is complete
image

**Comment by Howard20181** [comment]
If it is too difficult to implement we can switch to `Aria2`.

**Comment by m-jishnu** [comment]
> Now it's stuck in the WSA download is complete image

again it was because i didn't add a check to see completed in the last part fixed it

**Comment by m-jishnu** [comment]
> If it is too difficult to implement we can switch to `Aria2`.

let me try if its too hard lets do that, the downloader is 90% completed just some bugs here and there

**Comment by m-jishnu** [comment]
image

```
ARCH=x64
RELEASE_TYPE=insider fast
MAGISK_VER=stable
GAPPS_VARIANT=pico
REMOVE_AMAZON=remove
ROOT_SOL=magisk

Download WSA
Downloading Link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/1ee8f2d3-cfbe-4514-a83a-5aaadb44df5e?P1=1661255078&P2=404&P3=2&P4=DynZFVc%2b9wxUN1DBvAj1zNg2oPguMv69ZqsGq%2flDcfJ6W3ozt79qJBPK1pFenrisFI%2fv8dGVipKCzyuQDfzXHg%3d%3d to /mnt/f/Code/projects/python_projects/MagiskOnWSALocal/download/vclibs.appx
[████████████████████████████████████████████████████████████████████████████████████████████████████] 100% completed
0.82 MB downloaded, 0.82 MB total, 0.00 MB remaining, download speed: 1.58 MB/s
Downloading Link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/605edfa0-3ba9-423b-abb2-aa8da0b0e8f2?P1=1661255165&P2=404&P3=2&P4=XFSXKHm0Jvc723%2fRO59eU3Mb8aY2b0IKXpkc0PJ3sPoTebIfln5iuDRjIIO1DEWKz%2f2Z8TeS0EZscxEGt9vLqQ%3d%3d to /mnt/f/Code/projects/python_projects/MagiskOnWSALocal/download/xaml.appx
[████████████████████████████████████████████████████████████████████████████████████████████████████] 100% completed
4.65 MB downloaded, 4.65 MB total, 0.00 MB remaining, download speed: 0.13 MB/s
Downloading Link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/dad8ebbc-9e63-4ee6-8dfb-f12fd34669bf?P1=1661282777&P2=404&P3=2&P4=Righx7xw2sinL9QpwTszERYe66M2WYXCwSRnNGU%2b2WoKrEBMom%2fSZdNXeAY81nf1HgRLAXxgwuxOKg8bvTEzUg%3d%3d to /mnt/f/Code/projects/python_projects/MagiskOnWSALocal/download/wsa.zip
[█████████████████···················································································] 17% completed
239.75 MB downloaded, 1383.36 MB total, 1143.61 MB remaining, download speed: 0.00 MB/s
Traceback (most recent call last):
  File "downloadWSA.py", line 101, in <module>
    d.download(url,out_file)
  File "/mnt/f/Code/projects/python_projects/MagiskOnWSALocal/scripts/downloader.py", line 297, in download
    raise Exception("An error has occurred due to slow/no-internet connection")
Exception: An error has occurred due to slow/no-internet connection
Downloading Link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/dad8ebbc-9e63-4ee6-8dfb-f12fd34669bf?P1=1661282966&P2=404&P3=2&P4=m%2f8gQlX4hQik1U7kQacOSAeawXHt7q1Ipjd9cBNle%2bm0ef%2bA7ZdWeBQeEoWnoc1pr9kI4BvpeEJNsmFOmPbVEQ%3d%3d to /mnt/f/Code/projects/python_projects/MagiskOnWSALocal/download/wsa.zip
[███████████████████████████████████████████████████████████████████████████████████████████·········] 91% completed
1262.64 MB downloaded, 1383.36 MB total, 120.72 MB remaining, download speed: 0.00 MB/s
Traceback (most recent call last):
  File "downloadWSA.py", line 101, in <module>
    d.download(url,out_file)
  File "/mnt/f/Code/projects/python_projects/MagiskOnWSALocal/scripts/downloader.py", line 297, in download
    raise Exception("An error has occurred due to slow/no-internet connection")
Exception: An error has occurred due to slow/no-internet connection
Downloading Link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/dad8ebbc-9e63-4ee6-8dfb-f12fd34669bf?P1=1661283473&P2=404&P3=2&P4=VSEazQ3t8QJUEYhJnqkowE0tOMeMMLQs7ZLJfOQe1ncjJnvTDMtSxGzfUficQqyIsS4HMLHZTEjjhyM9L50hxg%3d%3d to /mnt/f/Code/projects/python_projects/MagiskOnWSALocal/download/wsa.zip
[████████████████████████████████████████████████████████████████████████████████████████████████████] 100% completed
1383.36 MB downloaded, 1383.36 MB total, 0.00 MB remaining, download speed: 1.52 MB/s
Download done

Extract WSA
unzipping to /tmp/wsa-build-gaN4h6CZnl_/wsa
unzipping from /tmp/wsa-build-gaN4h6CZnl_/wsa/WsaPackage_2206.40000.15.0_x64_Release-Nightly.msix
done
Extract done

Download Magisk
[████████████████████████████████████████████████████████████████████████████████████████████████████] 100% completed
10.76 MB downloaded, 10.76 MB total, 0.00 MB remaining, download speed: 0.63 MB/s
doneYPE=insider fast
MAGISK_VER=stable
GAPPS_VARIANT=pico
REMOVE_AMAZON=remove
ROOT_SOL=magisk

Download WSA
Downloading Link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/1ee8f2d3-cfbe-4514-a83a-5aaadb44df5e?P1=1661255078&P2=404&P3=2&P4=DynZFVc%2b9wxUN1DBvAj1zNg2oPguMv69ZqsGq%2flDcfJ6W3ozt79qJBPK1pFenrisFI%2fv8dGVipKCzyuQDfzXHg%3d%3d to /mnt/f/Code/projects/python_projects/MagiskOnWSALocal/download/vclibs.appx
[████████████████████████████████████████████████████████████████████████████████████████████████████] 100% completed
0.82 MB downloaded, 0.82 MB total, 0.00 MB remaining, download speed: 1.58 MB/s
Downloading Link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/605edfa0-3ba9-423b-abb2-aa8da0b0e8f2?P1=1661255165&P2=404&P3=2&P4=XFSXKHm0Jvc723%2fRO59eU3Mb8aY2b0IKXpkc0PJ3sPoTebIfln5iuDRjIIO1DEWKz%2f2Z8TeS0EZscxEGt9vLqQ%3d%3d to /mnt/f/Code/projects/python_projects/MagiskOnWSALocal/download/xaml.appx
[████████████████████████████████████████████████████████████████████████████████████████████████████] 100% completed
4.65 MB downloaded, 4.65 MB total, 0.00 MB remaining, download speed: 0.13 MB/s
Downloading Link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/dad8ebbc-9e63-4ee6-8dfb-f12fd34669bf?P1=1661282777&P2=404&P3=2&P4=Righx7xw2sinL9QpwTszERYe66M2WYXCwSRnNGU%2b2WoKrEBMom%2fSZdNXeAY81nf1HgRLAXxgwuxOKg8bvTEzUg%3d%3d to /mnt/f/Code/projects/python_projects/MagiskOnWSALocal/download/wsa.zip
[█████████████████···················································································] 17% completed
239.75 MB downloaded, 1383.36 MB total, 1143.61 MB remaining, download speed: 0.00 MB/s
Traceback (most recent call last):
  File "downloadWSA.py", line 101, in <module>
    d.download(url,out_file)
  File "/mnt/f/Code/projects/python_projects/MagiskOnWSALocal/scripts/downloader.py", line 297, in download
    raise Exception("An error has occurred due to slow/no-internet connection")
Exception: An error has occurred due to slow/no-internet connection
Downloading Link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/dad8ebbc-9e63-4ee6-8dfb-f12fd34669bf?P1=1661282966&P2=404&P3=2&P4=m%2f8gQlX4hQik1U7kQacOSAeawXHt7q1Ipjd9cBNle%2bm0ef%2bA7ZdWeBQeEoWnoc1pr9kI4BvpeEJNsmFOmPbVEQ%3d%3d to /mnt/f/Code/projects/python_projects/MagiskOnWSALocal/download/wsa.zip
[███████████████████████████████████████████████████████████████████████████████████████████·········] 91% completed
1262.64 MB downloaded, 1383.36 MB total, 120.72 MB remaining, download speed: 0.00 MB/s
Traceback (most recent call last):
  File "downloadWSA.py", line 101, in <module>
    d.download(url,out_file)
  File "/mnt/f/Code/projects/python_projects/MagiskOnWSALocal/scripts/downloader.py", line 297, in download
    raise Exception("An error has occurred due to slow/no-internet connection")
Exception: An error has occurred due to slow/no-internet connection
Downloading Link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/dad8ebbc-9e63-4ee6-8dfb-f12fd34669bf?P1=1661283473&P2=404&P3=2&P4=VSEazQ3t8QJUEYhJnqkowE0tOMeMMLQs7ZLJfOQe1ncjJnvTDMtSxGzfUficQqyIsS4HMLHZTEjjhyM9L50hxg%3d%3d to /mnt/f/Code/projects/python_projects/MagiskOnWSALocal/download/wsa.zip
[████████████████████████████████████████████████████████████████████████████████████████████████████] 100% completed
1383.36 MB downloaded, 1383.36 MB total, 0.00 MB remaining, download speed: 1.52 MB/s
Download done

Extract WSA
unzipping to /tmp/wsa-build-gaN4h6CZnl_/wsa
unzipping from /tmp/wsa-build-gaN4h6CZnl_/wsa/WsaPackage_2206.40000.15.0_x64_Release-Nightly.msix
done
Extract done

Download Magisk
[████████████████████████████████████████████████████████████████████████████████████████████████████] 100% completed
10.76 MB downloaded, 10.76 MB total, 0.00 MB remaining, download speed: 0.63 MB/s
done
```

seems to be working fine now

**Comment by m-jishnu** [comment]
@Howard20181 can you check now if its working or not

**Comment by m-jishnu** [comment]
- moved the retry to download again to bash  (run.sh)
- add more checks

**Comment by Howard20181** [comment]
It looks like Magisk does not retry after a failed download.
image
image

**Comment by Howard20181** [comment]
I try to switch to aria2.

**Comment by m-jishnu** [comment]
> I try to switch to aria2.

can it resume partially download ?

**Comment by m-jishnu** [comment]
> It looks like Magisk does not retry after a failed download. image image

fixed!

**Comment by m-jishnu** [comment]
> It looks like Magisk does not retry after a failed download. image image

fixed!

**Comment by m-jishnu** [comment]
> It looks like Magisk does not retry after a failed download. image image

fixed !
added retries on magisk can you check now

**Pull request closed without merging**
