### PR TITLE
Add batch script

### PR DESCRIPTION
**Pull request by s1204IT**
- `ps1` to `bat`
  - Can be open by double-clicking

- Removed credit for `ps1`.
  - User does not exist.
    https://github.com/doneibcn

- Fix some strings
  - There is no deep meaning to this.

- Putting files together
  - I've put additional files in the `MagiskOnWSA` folder.

And also...
Maybe I'm overlooking something.

### CODE REVIEW

**Comment by Howard20181** [comment]
We shouldn't remove the credit, just remove the dead link

**Comment by Howard20181** [comment]
In most cases Powershell scripts start with an uppercase command, do not change it to lowercase

**Comment by s1204IT** [comment]
> We shouldn't remove the credit, just remove the dead link

Now, I have fixed this.

> In most cases Powershell scripts start with an uppercase command, do not change it to lowercase

I thought so too.
But take a close look at the ps1 script before I commited.
The format of `If` and `ElseIf` is disjointed.

**Comment by s1204IT** [comment]
https://github.com/LSPosed/MagiskOnWSALocal/blob/main/scripts/build.sh#L702-L713
https://github.com/LSPosed/MagiskOnWSALocal/blob/main/scripts/build.sh#L736-L747

There are examples like this.

**Comment by s1204IT** [comment]
And one more thing, 

https://github.com/LSPosed/MagiskOnWSALocal/blob/main/scripts/build.sh#L679
https://github.com/LSPosed/MagiskOnWSALocal/blob/main/scripts/build.sh#L689

I've always hated the way this was written.

**Comment by s1204IT** [comment]
Why don't you separate them?
I thought it might be confusing for some users, so I purposely separated it.

**Comment by s1204IT** [comment]
It would be better to make the `ps1` directly callable.
I thought some users would be confused, so I purposely separated it.

**Comment by s1204IT** [comment]
It's a good idea.

**Pull request merged**
