### PR TITLE
Reveal `--depth` option

### PR DESCRIPTION
**Pull request by s1204IT**
Checklist
- [x] Have tested the modifications

---

It saves you from taking an inordinate amount of time when cloning.
Not all Git users know this, so it needs to be clearly stated.

### CODE REVIEW

**Comment by s1204IT** [comment]
And to make it easier to understand, I made the block bigger.

**Review by Howard20181 — APPROVED** [review]

**Comment by Almighty188** [comment]
Just a thought, in the instructions:
"How can I update WSA to a new version?

Delete the download folder Rerun the script, replace the content of your previous installation and rerun Install.ps1. Don't worry, your data will be preserved."

README.md says to use:
git clone https://github.com/LSPosed/MagiskOnWSALocal.git --depth 1
to clone the repo locally, is there a way to update the locally cloned repo so it is up to date without deleting the local repo first?

**Comment by Howard20181** [comment]
> Just a thought, in the instructions:
> "How can I update WSA to a new version?
> 
> Delete the download folder Rerun the script, replace the content of your previous installation and rerun Install.ps1. Don't worry, your data will be preserved."
> 
> README.md says to use:
> git clone https://github.com/LSPosed/MagiskOnWSALocal.git --depth 1
> to clone the repo locally, is there a way to update the locally cloned repo so it is up to date without deleting the local repo first?  
> 
> 

`git pull`

**Comment by Almighty188** [comment]
Thanks, I forgot to say maybe the answer to the FAQ question should be updated to:
Delete the download folder, run git pull https://github.com/LSPosed/MagiskOnWSALocal.git --depth 1,
Rerun the script, replace the content of your previous installation and rerun Install.ps1. Don't worry, your data will be preserved.

**Comment by Howard20181** [comment]
> Thanks, I forgot to say maybe the answer to the FAQ question should be updated to: Delete the download folder, run git pull [LSPosed/MagiskOnWSALocal.git](https://github.com/LSPosed/MagiskOnWSALocal.git) --depth 1, Rerun the script, replace the content of your previous installation and rerun Install.ps1. Don't worry, your data will be preserved.

But this is a basic use of git, and it's so basic that it shouldn't be in the FAQ.
And
Also, as a reminder, `git pull` doesn't require any arguments, so that link after the command is not needed.

**Comment by Almighty188** [comment]
The reason I mentioned the FAQ is there are people who visit for WSA that doesn't even have the basic knowledge of using git so if they used what is in the current FAQ, they will basically have an outdated repo.  You are right about git pull since it will pull the repo based on the current directory name or upper directory tree name.

**Pull request merged**
