### PR TITLE
Build x86_64 with MindTheGappsBuilder

### PR DESCRIPTION
**Pull request by s1204IT**
Made it "easy" to apply MindTheGapps on x86_64.

But I have some work to do.

- Build multiple architectures simultaneously, like the previous MagiskOnWSA
  - It is [not yet possible to get a direct link on androidfilehost](https://androidfilehost.com/api/docs/#folder).
    Therefore, it is necessary to respond with MindTheGappsBuilder.
  - Before adding it to the release draft, format the file name and change the tag name to a timestamp.
    This eliminates the need to rewrite the download URL.

- Need to format the scripts. 
  - The current state of affairs is not a very good way of writing by me.
    I need @Howard20181  help.

### CODE REVIEW

**Comment by Howard20181** [comment]
Please note that MindTheGappsBuilder may violate Actions' TOS and then be disabled by Github, just like MagiskOnWSA.
Having the download link written into the script will speed up the process. I don't want to put the download link in the script.

**Comment by Howard20181** [comment]
If you decide to use the repository as an api you can refer to the form of [magisk-file](https://github.com/topjohnwu/magisk-files).
Then indirectly accessed through a CDN such as Jsdelivr

**Comment by s1204IT** [comment]
I understand.
Tomorrow, we will change the URL acquisition method based on that.
Also, regarding arm64, I will put it on hold for now.

**Comment by Howard20181** [comment]
Jsdelivr has a file size limit.
https://github.com/jsdelivr/jsdelivr/issues/18268#issuecomment-748181483

**Comment by s1204IT** [comment]
Oh.
Absolutely over the limit.

**Comment by Howard20181** [comment]
Maybe we can try SourceForge

**Comment by s1204IT** [comment]
Then I can easily do it.
Including that, we will do it tomorrow.

**Comment by s1204IT** [comment]
Organize my progress along the way.

- Put a file in JSON format in the repository.
- Manually uploaded to SourceForge by me instead of a GitHub release.

**Comment by s1204IT** [comment]
Work completed.

- I created a script for MindTheGapps based on `generateGappsLink.py`.
- We originally made it possible to select MindTheGapps even if the MindTheGapps file does not exist.
- No JSON required, only SourceForge RSS.
  - Please let me know if @Howard20181 need the mirror.

I'm new to posting on SourceForge.
So, there may be deficiencies, so please point it out if you find one.

**Comment by s1204IT** [comment]
After...
Should I grant access for @Howard20181 to SourceForge?

**Comment by Howard20181** [comment]
It's up to you

**Comment by s1204IT** [comment]
> It's up to you

I understand.
If you give us your username, we will invite you.

**Comment by Howard20181** [comment]
> > It's up to you
> 
> I understand. If you give us your username, we will invite you.

Username: howardwu

**Comment by s1204IT** [comment]
> > > It's up to you
> > 
> > 
> > I understand. If you give us your username, we will invite you.
> 
> Username: howardwu

Invited.

**Comment by s1204IT** [comment]
@Howard20181
https://github.com/LSPosed/MagiskOnWSALocal/pull/62#issuecomment-1342019109
I'm trying to add a package of API33 to SourceForge.
But if I do it now, I can expect package parsing errors in the WSA of API32.

I want to hear your opinion.

**Comment by Howard20181** [comment]
@s1204IT The last change pushed should handle this

**Comment by s1204IT** [comment]
@Howard20181
I think I need to identify the API level of the WSA before downloading GApps.
So, identify the API level from the filename of the MsixBundle to be downloaded.


Before "**2203**" or "**1.\*.\***"
11 (30)

"**2204**" ~ "**2210**"
12.1 (32)

After "**2211**"
13 (33)

**Comment by Howard20181** [comment]
This has now been done and is now not available for download to Android 11, so it is mapped from Android 12.1.

**Comment by s1204IT** [comment]
Part of the log:
```
COMMAND_LINE=--arch x64 --release-type WIF --magisk-ver beta --gapps-brand MindTheGapps --gapps-variant pico --remove-amazon --root-sol magisk     --compress-format
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: beta
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Insider Fast
Generate Download Links
Generating WSA download link: arch=x64 release_type=Insider Fast
download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/605edfa0-3ba9-423b-abb2-aa8da0b0e8f2?P1=1670498565&P2=404&P3=2&P4=m5MbCQOppistILPUmREZqV0DmonnOFPNGd87QUUzQJfsEoQBp%2bdPLx%2fwEGbNG1ryaufq5c7n%2fvd2pWm3N%2bf7%2bg%3d%3d to /home/s1204it/MagiskOnWSALocal/download/Microsoft.UI.Xaml_x64.appx
download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/15af34f3-b0f6-42bb-9e95-19888b0c545c?P1=1670526226&P2=404&P3=2&P4=d7rKM7zQ2wyoMQxAgP1B5IrOeW0XfsZDOoEgslwZqRQQ6FAsH9IOB27UBtv%2fWWS5AJ2avSceJh8NfModnlmtRQ%3d%3d to /home/s1204it/MagiskOnWSALocal/download/wsa-WIF.zip
Generating Magisk download link: release type=beta
download link: https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@25.2/app-release.apk
Generating MindTheGapps download link: arch=x64 variant=pico
download link: https://downloads.sourceforge.net/project/wsa-mtg/x86_64/20221208/MindTheGapps-13.0.0-x86_64-20221208_045947.zip
Download Artifacts

[DL:16MiB][#47e92c 1.3MiB/4.6MiB(28%)][#8830c1 9.1MiB/1.3GiB(0%)][#a80763 0B/0B][#1557f0 176KiB/10MiB(1%)][
12/08 10:53:19 [NOTICE] CUID#11 - Redirecting to https://nchc.dl.sourceforge.net/project/wsa-mtg/x86_64/20221208/MindTheGapps-13.0.0-x86_64-20221208_045947.zip

[DL:19MiB][#8830c1 1.3GiB/1.3GiB(99%)][#a19b9d 93MiB/188MiB(49%)]
12/08 10:54:32 [NOTICE] Download complete: /home/s1204it/MagiskOnWSALocal/download/wsa-WIF.zip
[#a19b9d 187MiB/188MiB(99%) CN:1 DL:4.4MiB]
12/08 10:54:51 [NOTICE] Download complete: /home/s1204it/MagiskOnWSALocal/download/MindTheGapps-x64-12.1.zip

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
8830c1|OK  |    18MiB/s|/home/s1204it/MagiskOnWSALocal/download/wsa-WIF.zip
a19b9d|OK  |   2.0MiB/s|/home/s1204it/MagiskOnWSALocal/download/MindTheGapps-x64-12.1.zip
```

2210 is "**12.1**", but "**13**" file have been downloaded.

Waiting for your help at SourceForge.

**Pull request merged**
