### PR TITLE
Delete apps no longer need

### PR DESCRIPTION
**Pull request by s1204IT**
#### Checklist
- [x] Have tested the modifications

---
I did an operation check on both OpenGApps and MindTheGapps.
There were no issues where the Play Store stopped launching or crashed suddenly.

Also, `VPNDialogs` issue should [already be fixed](https://learn.microsoft.com/en-us/windows/android/wsa/release-notes#build-220540000140), but I haven't made any changes because I can't verify it.

### CODE REVIEW

**Comment by Howard20181** [comment]
As far as I know, `VPN Dialogs` have not been fixed. You can test and try to create a new connection using VPN in WSA

**Comment by Howard20181** [comment]
The SetupWizard is from AOSP
The reason why we used it to replace the version from Google (included in GApps) before was that the Google version would cause the system to crash. We did not test whether the new version was OK.

**Comment by s1204IT** [comment]
> As far as I know, `VPN Dialogs` have not been fixed. You can test and try to create a new connection using VPN in WSA

I understand.

> The SetupWizard is from AOSP The reason why we used it to replace the version from Google (included in GApps) before was that the Google version would cause the system to crash. We did not test whether the new version was OK.

At least it didn't have that problem with MindTheGapps.

Does this mean that OpenGApps has not been updated since 20220215, so similar crashes may occur?

**Comment by Howard20181** [comment]
> Does this mean that OpenGApps has not been updated since 20220215, so similar crashes may occur?

Previously, when WSA was still Android 11, the system would crash
Not tested since WSA was updated to Android 12.1

**Comment by s1204IT** [comment]
> > Does this mean that OpenGApps has not been updated since 20220215, so similar crashes may occur?
> 
> Previously, when WSA was still Android 11, the system would crash Not tested since WSA was updated to Android 12.1

However, as my friends and I have verified, there was no crashing issue.
We think 2207~2209 seems to have no problem.

**Comment by Howard20181** [comment]
> there was no crashing issue.

Is it in the case of the fresh installation?
Will test it later

**Comment by s1204IT** [comment]
> > there was no crashing issue.
> 
> Is it in the case of the fresh installation?
> Will test it later

It is a fresh installation.
Thank you for your verifying

**Pull request merged**
