### PR TITLE
Modify scanning destination

### PR DESCRIPTION
**Pull request by s1204IT**
I don't know what the purpose of this is for me, but...

Fixed workflow.

### CODE REVIEW

**Comment by s1204IT** [comment]
https://github.com/LSPosed/MagiskOnWSALocal/actions/runs/3455112979/jobs/5766890644#step:3:175
```
find: ‘./scripts/*.sh’: No such file or directory
```
🤔

**Comment by Howard20181** [comment]
You don't need to add the suffix, it will cause the check not to work.
In fact the script now has a warning that it is normal not to pass the check.

**Comment by s1204IT** [comment]
https://github.com/LSPosed/MagiskOnWSALocal/actions/runs/3455131162
Great.

**Comment by Howard20181** [comment]
https://www.shellcheck.net/wiki/SC2086
Properly speaking it should not be ignored, but I can't think of a better way to solve the problem with the `$SUDO` variable.

**Pull request closed without merging**
